# -*- coding: utf-8 -*-
"""phishing_distilbert_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J2dECCjddj87NzHfZMuen6aH2ry4aQyH
"""

from google.colab import drive
drive.mount('/content/drive')

!cp /content/drive/MyDrive/enron_phishing.zip /content/

!unzip enron_phishing.zip

!ls

import pandas as pd

df = pd.read_csv("emails.csv")

df.head()

df.info()

!unzip phishing_datasets.zip
!ls phishing_datasets

"""Let us start with data inspection and bring all the datasets in one single format that is email,1/0 for phishing so lets get started with ceas_08.csv file"""

import pandas as pd

ceas = pd.read_csv("/content/CEAS_08.csv")

ceas.shape

ceas.columns

ceas.info()

ceas['label'].value_counts()

"""so dataset is not very imbalanced which is good for us,now we need the format text | label,where text should have subject+body,so let us do it now

"""

ceas['text'] = ceas['subject'].fillna('') + ' ' + ceas['body'].fillna('')

ceas_final = ceas[['text', 'label']]
#removing all other unnessary ones

ceas_final.shape

ceas_final.isnull().sum()
#checking nulls

ceas_final.to_csv("CEAS_08_standardized.csv", index=False)

"""We standardized the CEAS_08 dataset by concatenating subject and body fields into a single text column and retaining the original binary label, ensuring a uniform input representation for transformer-based models.

2.LING.CSV lets start analysing it
"""

import pandas as pd

ling = pd.read_csv("/content/Ling.csv")

ling.shape

"""so it has 3 columns and 3k rows let us see what columns are there"""

ling.columns
ling.head()

ling['label'].value_counts()

ling['text'] = ling['subject'].fillna('') + ' ' + ling['body'].fillna('')

ling_final = ling[['text', 'label']]

ling_final.shape
ling_final.isnull().sum()

ling_final.to_csv("Ling_standardized.csv", index=False)

"""Nazario.csv this is 3rd file"""



import pandas as pd

nazario = pd.read_csv("/content/Nazario.csv")

nazario.shape

"""so this has 1500 rows and 7 cols let us see col names"""

nazario.columns

nazario['label'].value_counts()

"""This has only phishing emails"""

nazario['text'] = nazario['subject'].fillna('') + ' ' + nazario['body'].fillna('')

nazario_final = nazario[['text', 'label']]

nazario_final.shape
nazario_final.isnull().sum()

nazario_final.to_csv("Nazario_standardized.csv", index=False)

"""Now the 4th dataset ie nigerian_fraud dataset"""

import pandas as pd

nigerian = pd.read_csv("/content/Nigerian_Fraud.csv")

nigerian.shape

nigerian.columns

nigerian.info()

nigerian['label'].value_counts()

"""This too is a phishing only dataset"""

nigerian['text'] = nigerian['subject'].fillna('') + ' ' + nigerian['body'].fillna('')

nigerian_final = nigerian[['text', 'label']]

nigerian_final.shape
nigerian_final.isnull().sum()

nigerian_final.to_csv("Nigerian_Fraud_standardized.csv", index=False)

"""spam assassin dataset"""

import pandas as pd

spam = pd.read_csv("/content/SpamAssassin.csv")

spam.shape

spam.columns

spam.head()

spam['label'].value_counts()

spam['text'] = spam['subject'].fillna('') + ' ' + spam['body'].fillna('')

spam_final = spam[['text', 'label']]

spam_final.shape
spam_final.isnull().sum()

spam_final.to_csv("SpamAssassin_standardized.csv", index=False)

"""8th one phishing_email.csv file"""

import pandas as pd

phish = pd.read_csv("/content/phishing_email.csv")

phish.shape

phish.columns

phish.head()

phish_final = phish.rename(columns={"text_combined": "text"})

phish_final = phish_final[['text', 'label']]

phish_final.shape
phish_final.isnull().sum()

phish_final.to_csv("phishing_email_standardized.csv", index=False)

"""ok so all datasets ready now let us combine all standarizided data into one piece"""

import pandas as pd

ceas = pd.read_csv("CEAS_08_standardized.csv")
ling = pd.read_csv("Ling_standardized.csv")
nazario = pd.read_csv("Nazario_standardized.csv")
nigerian = pd.read_csv("Nigerian_Fraud_standardized.csv")
spam = pd.read_csv("SpamAssassin_standardized.csv")
phish = pd.read_csv("phishing_email_standardized.csv")

print(ceas.columns, ling.columns, nazario.columns, nigerian.columns, spam.columns, phish.columns)

master_df = pd.concat(
    [ceas, ling, nazario, nigerian, spam, phish],
    axis=0,
    ignore_index=True
)

master_df = master_df.sample(frac=1, random_state=42).reset_index(drop=True)

master_df.shape

master_df['label'].value_counts()

master_df.to_csv("phishing_master_dataset.csv", index=False)

"""What we WILL do (safe & standard)
1️⃣ Convert text to lowercase

Why:

Reduces vocabulary size

Transformers handle lowercase well

2️⃣ Remove extra whitespace

Why:

Emails often have broken formatting

Improves token consistency

3️⃣ Remove non-printable characters

Why:

Some datasets contain hidden control characters

These cause tokenizer noise

4️⃣ Keep everything else

Especially:

URLs

email addresses

numbers

urgency words

scam templates

Lets start some light text standardization
"""

import re

def clean_text_light(text):
    if not isinstance(text, str):
        return ""

    # lowercase
    text = text.lower()

    # remove non-printable characters
    text = re.sub(r'[^\x20-\x7E]', ' ', text)

    # normalize whitespace
    text = re.sub(r'\s+', ' ', text).strip()

    return text
master_df['text_clean'] = master_df['text'].apply(clean_text_light)

master_df[['text', 'text_clean']].head(5)

master_df = master_df[['text_clean', 'label']]
master_df = master_df.rename(columns={'text_clean': 'text'})

master_df.isnull().sum()

master_df.isnull().sum()
master_df.head()

master_df.to_csv("phishing_master_dataset_cleaned.csv", index=False)

"""now lets sart train validation and test split in ratio 80 10 10

"""

from sklearn.model_selection import train_test_split

X = master_df['text']
y = master_df['label']

X_train, X_temp, y_train, y_temp = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

X_val, X_test, y_val, y_test = train_test_split(
    X_temp,
    y_temp,
    test_size=0.50,
    random_state=42,
    stratify=y_temp
)

print("Train size:", len(X_train))
print("Validation size:", len(X_val))
print("Test size:", len(X_test))

print("Train labels:\n", y_train.value_counts(normalize=True))
print("\nValidation labels:\n", y_val.value_counts(normalize=True))
print("\nTest labels:\n", y_test.value_counts(normalize=True))

train_df = pd.DataFrame({'text': X_train, 'label': y_train})
val_df   = pd.DataFrame({'text': X_val, 'label': y_val})
test_df  = pd.DataFrame({'text': X_test, 'label': y_test})

train_df.to_csv("train.csv", index=False)
val_df.to_csv("val.csv", index=False)
test_df.to_csv("test.csv", index=False)

"""now completed:

✔ Dataset collection

✔ Cleaning & standardization

✔ Merging

✔ Balanced splitting

✔ ML-ready data preparation

DistilBERT
| Reason                       | Why it matters                         |
| ---------------------------- | -------------------------------------- |
| Transformer-based            | Understands context, intent, deception |
| 40% smaller than BERT        | Faster training                        |
| 60% faster inference         | Good for real-time dashboard           |
| Pretrained on large corpus   | Needs less data                        |
| Widely accepted academically | Strong viva credibility                |


distilbert-base-uncased

Architecture Overview (what actually happens)
Input
Email text


⬇️ Tokenizer

Converts text → tokens

Adds attention masks

Handles variable length

⬇️ DistilBERT Encoder

6 transformer layers

Captures:

Urgency

Impersonation

Social engineering

Threat language

⬇️ Classification Head

Dense layer

Softmax / Sigmoid output

Binary prediction

⬇️ Output

Phishing probability + label

📌 Output We Will Generate (important)

model will output:

prediction: 0 or 1

confidence score: e.g., 0.87

severity mapping:

Low

Medium

High

This directly feeds Crime Signature Fusion Engine.

We selected DistilBERT because it preserves most of BERT’s language understanding capabilities while being computationally efficient, making it suitable for real-time cyber forensics applications
"""

#So tokenization start from now,let us use hugging face tokenizer DistilBertTokenizerFast

!pip install transformers datasets torch

import pandas as pd
import torch
from transformers import DistilBertTokenizerFast

tokenizer = DistilBertTokenizerFast.from_pretrained(
    "distilbert-base-uncased"
)

def tokenize_texts(texts):
    return tokenizer(
        texts.tolist(),
        truncation=True,
        padding=True,
        max_length=256
    )

import pandas as pd

train_df = pd.read_csv("train.csv")
val_df   = pd.read_csv("val.csv")
test_df  = pd.read_csv("test.csv")

def clean_text_column(df):
    df = df.copy()
    df['text'] = df['text'].astype(str)
    df['text'] = df['text'].fillna("")
    df = df[df['text'].str.strip() != ""]
    return df
train_df = clean_text_column(train_df)
val_df   = clean_text_column(val_df)
test_df  = clean_text_column(test_df)
print(train_df['text'].isna().sum())
print((train_df['text'].str.strip() == "").sum())
def downsample(df, samples_per_class):
    return (
        df.groupby('label', group_keys=False)
          .apply(lambda x: x.sample(min(len(x), samples_per_class), random_state=42))
          .sample(frac=1, random_state=42)
          .reset_index(drop=True)
    )
train_df = downsample(train_df, samples_per_class=15000)
val_df   = downsample(val_df, samples_per_class=3000)
test_df  = downsample(test_df, samples_per_class=3000)
print("Train:", train_df.shape)
print("Val:", val_df.shape)
print("Test:", test_df.shape)

print(train_df['label'].value_counts())

"""To handle memory constraints, we downsampled the dataset in a class-balanced manner, ensuring equal representation of phishing and legitimate emails while preserving model performance."""

train_df.to_csv("train_small.csv", index=False)
val_df.to_csv("val_small.csv", index=False)
test_df.to_csv("test_small.csv", index=False)

train_encodings = tokenize_texts(train_df['text'])
train_labels = torch.tensor(train_df['label'].values)
val_encodings = tokenize_texts(val_df['text'])
val_labels = torch.tensor(val_df['label'].values)
test_encodings = tokenize_texts(test_df['text'])
test_labels = torch.tensor(test_df['label'].values)

class EmailDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item['labels'] = self.labels[idx]
        return item

    def __len__(self):
        return len(self.labels)

train_dataset = EmailDataset(train_encodings, train_labels)
val_dataset   = EmailDataset(val_encodings, val_labels)
test_dataset  = EmailDataset(test_encodings, test_labels)

"""now starts training"""

!pip install -q transformers torch scikit-learn accelerate
!pip install -U transformers accelerate

import pandas as pd
import numpy as np
import torch

from sklearn.metrics import accuracy_score, precision_recall_fscore_support
from transformers import (
    DistilBertTokenizerFast,
    DistilBertForSequenceClassification,
    Trainer,
    TrainingArguments
)

tokenizer = DistilBertTokenizerFast.from_pretrained(
    "distilbert-base-uncased"
)

model = DistilBertForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=2
)

model.to("cuda")

def compute_metrics(pred):
    labels = pred.label_ids
    preds = np.argmax(pred.predictions, axis=1)

    precision, recall, f1, _ = precision_recall_fscore_support(
        labels, preds, average="binary"
    )
    acc = accuracy_score(labels, preds)

    return {
        "accuracy": acc,
        "precision": precision,
        "recall": recall,
        "f1": f1
    }



training_args = TrainingArguments(
    output_dir="./results",
    eval_strategy="epoch",          # <-- updated keyword
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=3,
    weight_decay=0.01,
    logging_steps=100,
    load_best_model_at_end=True,
    metric_for_best_model="f1",
    fp16=True,
    report_to="none"
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    tokenizer=tokenizer,
    compute_metrics=compute_metrics
)

trainer.train()

trainer.evaluate(test_dataset)

model.save_pretrained("phishing_distilbert_model")
tokenizer.save_pretrained("phishing_distilbert_model")

!zip -r phishing_distilbert_model.zip phishing_distilbert_model

!ls -lh phishing_distilbert_model.zip

from google.colab import drive
drive.mount('/content/drive')

!cp phishing_distilbert_model.zip /content/drive/MyDrive/